### PR TITLE
#32 Added basic contribution guidelines

### PR DESCRIPTION
**Pull request by alavkx**
Getting started with making a contribution to the project. A how-to with a few bits of advice on making a good PR. Tried to make the description friendly to new oss contributors...considering I'm part of that group.

Thanks and credit goes to @TalAter. I referenced his post here: https://github.com/TalAter/Progressive-UI-KITT/issues/1 to make the guidelines.

### CODE REVIEW

**Comment by davidnaas** [comment]
Good initiative! It would also be nice to have a part more focused on the stylistic rather than technical parts of commits and pr flow to keep a consistent history!

**Comment by alavkx** [comment]
I'll do that next! Let me know of anything specific you want included.
Otherwise I'll just reference other repos contrib files and cross my fingers.

**Comment by davidnaas** [comment]
I think that's for @kenwheeler to decide. I just want something to lean against :)

**Comment by TalAter** [comment]
Thanks for the mention @alavkx 👍 
You might also want to have a look at the contribution guide itself: https://github.com/TalAter/annyang/blob/master/CONTRIBUTING.md

**Comment by kenwheeler** [comment]
Awesome! Re: style, I'll get lint/test CI in place and that should manage that.

**Comment by alavkx** [comment]
That would be a good place to start wouldn't it.. Ha. Thanks @talater

**Pull request merged**
